language: node_js
node_js:
  - "6.0.0"
  - "6.9.5"
  - "7.0.0"
  - "7.5.0"
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
  - npm run coverage
  - npm run coveralls
